### ISSUE TITLE
Add warning5654 to troubleshooting section

### ISSUE THREAD

**Issue by callhands** [StudentShop/Trak-Lathe-Guide#5]
A student mistakenly entered a chamfer instead of a conrad when boring the internal profile of CNC Lathe 1 part 3. They were presented the following error message:
"Warning5654:Data Error around event # Cannot tool apply tool compensation on event data Check and edit event data"
This message and the possible solution should be added to the troubleshooting section.

**Comment by rmark66** [comment]
Added "Warning5654:Data Error around event # Cannot tool apply tool compensation on event data Check and edit event data" to Trouble Shooting page.
